# exp configs
local_rank: 0
amp: true
seed: 42

# logging and checkpoints
log_wandb: false
experiment: vit_base_patch16_224_mae_lp
output: ''
log_interval: 50
recovery_interval: 0

# model configs
model: vit_base_patch16_224_mae
pretrained: true
drop: 0.0
drop_path: 0.1 

# training configs
linear_prob: true

sync_bn: false
dist_bn: reduce
batch_size: 128
epochs: 90

# dataloader
workers: 4
pin_mem: false
train_split: train
val_split: validation
validation_batch_size: null

# lr
lr: 0.4
sched: cosine
warmup_epochs: 10
warmup_lr: 0.0001
cooldown_epochs: 0
min_lr: 1.0e-06

# optimizer
opt: sgd
opt_betas: null
opt_eps: null
weight_decay: 0.0
momentum: 0.9
accum_iter: 1

# data aug
#aa: rand-m9-mstd0.5-inc1
aug_repeats: 0
aug_splits: 0
color_jitter: 0.0
hflip: 0.5
vflip: 0.0
img_size: null
interpolation: ''
scale:
- 0.08
- 1.0
ratio:
- 0.75
- 1.3333333333333333
smoothing: 0.1 # label smoothing

# resume
initial_checkpoint: ''
resume: ''
start_epoch: null
