name: bbclassification
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch==1.12.1
  - torchvision==0.13.1 
  - torchaudio==0.12.1 
  - cudatoolkit=11.3
  - python==3.9
  - numpy
  - scipy
  - scikit-learn
  - pip
  - pip:
    - git+https://github.com/openai/CLIP.git
    - timm==0.6.12
    - transformers
    - omegaconf
    - opencv-python
    - wandb
    - einops
    - wilds
    - pytorch_lightning
    - tensorboard
