from .vit_mae import *
from .resnet_clip import *
from .resnet_dino import *
from .stable_diff import *
from .vit_clip import *
from .vicreg import *
from .vicregl import *
from .mocov3 import *
from .midas_encoder import *
